name: Deploy React App to S3

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'  # Choose the version compatible with your app

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Sync to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'  # Set your region
        run: |
          aws s3 sync ./build s3://react-cra-static-website-hosting --delete --region ${{ secrets.AWS_REGION }}
